### PR TITLE
Adapt the logo to dark mode

### PR DESCRIPTION
**Pull request by spacedawwwg**
image

### CODE REVIEW

**Comment by sindresorhus** [comment]
It doesn't seem to work when I look at https://github.com/spacedawwwg/modern-normalize/blob/patch-2/readme.md in dark mode.

**Comment by spacedawwwg** [comment]
image

**Comment by sindresorhus** [comment]
Go to https://github.com/spacedawwwg/modern-normalize/tree/patch-2 when in dark mode, and then change the system to light mode. The text does not update. It only updates after a page refresh.

**Comment by spacedawwwg** [comment]
@sindresorhus that's a known bug with chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1093736

**Comment by sindresorhus** [comment]
Thanks :)

**Comment by JoCat** [comment]
There is one problem, this edit does not take into account the following use case: with a light theme on the github and a dark theme in the system and vice versa. 😅

**Pull request merged**
