### PR TITLE
Improve consistency of default fonts

### LINKED ISSUE #3: Provide system fonts
Are there any downsides to setting this by default?

```css
body {
	font-family:
		'-apple-system',
		'system-ui',
		'BlinkMacSystemFont',
		'Segoe UI',
		'Roboto',
		'Helvetica Neue',
		'Arial',
		'sans-serif',
		'Apple Color Emoji',
		'Segoe UI Emoji',
		'Segoe UI Symbol';
}
```

Users then get good defaults but can override it with their own `body` selector if they want.

Alternatively, if this gets a lot of resistance, we could provide a CSS variable, so users who want it can just do:

```css
body {
	font-family: var(--system-fonts);
}
```

Thoughts?

*(If you 👎 please also share your thoughts on why)*

### PR DESCRIPTION
**Pull request by sindresorhus**
Fixes #3 

Note to self: Open an issue about including `system-ui` if this PR is merged.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Unless the relatavely new stack by Github should be incorporated here

What do you mean? This is using GitHub's exact stack.

**Comment by anselmh** [comment]
😶 I see it from the source code now. Now the entire blog post ist only confusing to me, it seems I completely misinterpreted it, including my statement about Helvetica (I still don’t get github’s decision on that then). What means the Pull Request changes here are totally fine without any concerns.

**Comment by Haroenv** [comment]
👍

**Comment by mdo** [comment]
Y'all should reach out to our Design Systems team (pinging @broccolini) and the Chrome devs. They reached out to us about moving away from the Blink specific font name there, but we had our own challenges when attempting that several months ago I believe.

**Comment by broccolini** [comment]
Here's a pr I started which includes some info on the font stack: https://github.com/primer/primer/pull/408 re removing `BlinkMacSystemFont`. I haven't continued as there hasn't been much follow up from the Chrome folks, and there's not a clear positive solution that works for everyone.

**Comment by sindresorhus** [comment]
Seems like the safest bet is to stick with what's here until https://github.com/primer/primer/pull/408 is resolved or we hear back from Chrome devs. I'll try to ping some people I know.

**Comment by sindresorhus** [comment]
Continued in https://github.com/sindresorhus/modern-normalize/issues/18.

**Pull request merged**
