### PR TITLE
Add acceptance tests

### LINKED ISSUE #1: Remove more outdated styles
I've already removed a lot of outdated styles (https://github.com/sindresorhus/modern-normalize/commit/c2e7aa3009b2a2391fabca66326a88bbffd16acf https://github.com/sindresorhus/modern-normalize/commit/b52144d04b756539ac5ac8734213ed812f349d2a), but I'm sure there are more things that are fixed in browsers by now. We should go through the styles and check whether they're still valid in latest Chrome and Firefox.

### LINKED ISSUE #22: Add some tests
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/modern-normalize/issues/22)

It could be useful for this project to stay up to date with the default values of the declarations which are normalized here within the supported browsers.

This should be possible by testing the output of `window.getComputedStyle()` against what is expected from each browser, and the results can be used to remove rules which are no longer needed in recent versions.

If we want to be more ambitious, it can potentially also be used to find new differences between other elements that should potentially be normalized as well.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#35 Add acceptance tests](https://issuehunt.io/r/sindresorhus/modern-normalize/pull/35)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/modern-normalize/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by rafaelfbs**
A starting point to create acceptance tests and to validate outdated styles (will close #1, close #22)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#22: Add some tests](https://issuehunt.io/repos/120715537/issues/22)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by rafaelfbs** [comment]
We need to figure out a way to test in safari. Maybe using [BrowserStack](https://www.browserstack.com/open-source)?

**Comment by sindresorhus** [comment]
Travis supports `osx` as an OS, which has Safari.

**Comment by rafaelfbs** [comment]
> Travis supports `osx` as an OS, which has Safari.

Worked like a charm :relaxed:

**Comment by rafaelfbs** [comment]
There are some future issues:
- Validate some inconsistencies in safari (text-decoration)
- Testcafe does not support pseudo-elements selector (https://github.com/DevExpress/testcafe/issues/2813)

Even so, everything seems to be alright. @sindresorhus @Zirro

**Comment by sindresorhus** [comment]
Why are there duplicate test files for each browser?

**Comment by rafaelfbs** [comment]
Each browser has it's own style property values, like some _line-heights_ and vendor properties (_-webkit-appearance, -webkit-text-size-adjust, -moz-tab-size_). What's more, we need to run some assertions that is valid only in one browser, like "Remove the inner border and padding in Firefox.", that does not even exists on chrome and safari (-moz-focus-inner).

I've sepparated the tests into two types. The `rules.ts` files are assertions in a page loading the `modern-normalize` CSS, the objective is to assert if the given rule is applied correctly. The `validation.ts` files are assertions in a page without the CSS module, the objective is to catch the changes on the newest browsers versions and remove the old rules.

I would really appreciate some feedback and improvements. It was troublesome to test some scenarios like safari's font on different platforms (my pc vs travis mac). :grin:

**Comment by sindresorhus** [comment]
@rafaelfbs Sorry for leaving this for so long. I just had to many PRs to review. Can you fix the failing tests?

**Comment by rafaelfbs** [comment]
@sindresorhus Tests passing.

**Comment by sindresorhus** [comment]
Looking good. Thanks for working on this ❤️

**Pull request merged**
