### PR TITLE
Add link to usage with styled-components

### PR DESCRIPTION
**Pull request by sergeysova**

### CODE REVIEW

**Comment by sindresorhus** [comment]
What do you think about `modern-normalize` shipping with a JS file that just exports the CSS in a string? That would make it easier for you to keep it update to date, right? Is there any way to make it fully compatible with styled-components without having to import `styled-components`?

**Comment by sindresorhus** [comment]
// @t-lock ⬆️

**Comment by sergeysova** [comment]
@sindresorhus You're right.

```js
export const normalize = `
  css here
`
```

```js
import { normalize } from 'modern-normalize/cssinjs'
import { createGlobalStyle } from 'styled-components'

const Normalize = createGlobalStyle`
  ${normalize}
`
```

**Comment by sindresorhus** [comment]
@sergeysova Yeah, I like that.

We could actually ship support for `styled-components` too:

```js
import normalize from 'modern-normalize/styled-components';
```

The `styled-components.js` file would be what you have above, but we would not depend on `styled-components` as a dependency, instead expecting you too, which is fine.

**Comment by oyeanuj** [comment]
@sindresorhus Your solution would be ideal!

**Comment by polarathene** [comment]
There is [`styled-modern-normalize`](https://github.com/arcticicestudio/styled-modern-normalize)for this btw, but it's a bit out of date now. It uses `modern-normalize` `0.50`, and hasn't been updated for the v5 release of `styled-components`(no issues, just `package.json` peer dependency needs update), so it's probably better if that could be maintained here if possible, less likely to fall out of sync then.

**Comment by sindresorhus** [comment]
> If the proposal here is just to provide the template string, then it doesn't need to have any mention of styled-components, could use a more generic name as other CSS-in-JS packages like Linaria could use it too afaik.

Correct

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/sindresorhus/modern-normalize/issues/44.

**Pull request closed without merging**
